-- Core tables for stocktrace
-- Uses GENERATED BY DEFAULT AS IDENTITY (SQL standard) which H2 and Postgres both support.

CREATE TABLE kite_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL UNIQUE,
    label VARCHAR(128),
    api_key VARCHAR(128) NOT NULL,
    api_secret VARCHAR(256) NOT NULL,
    access_token VARCHAR(256),
    public_token VARCHAR(256),
    access_token_expires_at TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    default_exchange VARCHAR(16) NOT NULL DEFAULT 'NSE',
    default_product VARCHAR(16) NOT NULL DEFAULT 'CNC',
    default_order_type VARCHAR(16) NOT NULL DEFAULT 'MARKET',
    default_quantity INT NOT NULL DEFAULT 1,
    default_variety VARCHAR(16) NOT NULL DEFAULT 'regular',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kite_users_active ON kite_users(active);

CREATE TABLE order_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kite_user_id VARCHAR(64) NOT NULL,
    source VARCHAR(32) NOT NULL,
    tradingsymbol VARCHAR(64) NOT NULL,
    exchange VARCHAR(16) NOT NULL,
    transaction_type VARCHAR(8) NOT NULL,
    order_type VARCHAR(16) NOT NULL,
    product VARCHAR(16) NOT NULL,
    quantity INT NOT NULL,
    price DOUBLE PRECISION,
    trigger_price DOUBLE PRECISION,
    broker_order_id VARCHAR(64),
    status VARCHAR(16) NOT NULL,
    error_message VARCHAR(1024),
    request_json TEXT,
    response_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_order_audit_user ON order_audit(kite_user_id);
CREATE INDEX idx_order_audit_created ON order_audit(created_at);

CREATE TABLE scan_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    exchange VARCHAR(16) NOT NULL,
    tradingsymbol VARCHAR(64) NOT NULL,
    instrument_token BIGINT,
    condition_type VARCHAR(32) NOT NULL,
    threshold_low DOUBLE PRECISION,
    threshold_high DOUBLE PRECISION,
    transaction_type VARCHAR(8) NOT NULL DEFAULT 'BUY',
    quantity INT NOT NULL DEFAULT 1,
    product VARCHAR(16) NOT NULL DEFAULT 'CNC',
    order_type VARCHAR(16) NOT NULL DEFAULT 'MARKET',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_triggered_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scan_rule_active ON scan_rule(active);

CREATE TABLE tick_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kite_user_id VARCHAR(64) NOT NULL,
    instrument_token BIGINT NOT NULL,
    last_price DOUBLE PRECISION,
    volume_traded_today BIGINT,
    exchange_timestamp TIMESTAMP,
    tick_timestamp TIMESTAMP,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tick_log_token ON tick_log(instrument_token);
CREATE INDEX idx_tick_log_received ON tick_log(received_at);

CREATE TABLE webhook_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(32) NOT NULL,
    payload TEXT NOT NULL,
    scan_name VARCHAR(256),
    alert_name VARCHAR(256),
    stocks VARCHAR(1024),
    trigger_prices VARCHAR(1024),
    triggered_at VARCHAR(64),
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_webhook_event_received ON webhook_event(received_at);
