-- 5paisa user accounts.
-- 5paisa auth differs significantly from Kite: it requires AppConfig fields
-- (encryption key + user key + app name/version) plus per-call client_code, and
-- the session is a JWT minted from a TOTP exchange. Hence a separate table.

CREATE TABLE fivepaisa_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL UNIQUE,
    label VARCHAR(128),
    app_name VARCHAR(64) NOT NULL,
    app_ver VARCHAR(16) NOT NULL DEFAULT '1.0',
    os_name VARCHAR(16) NOT NULL DEFAULT 'WEB',
    encrypt_key VARCHAR(128) NOT NULL,
    user_key VARCHAR(128) NOT NULL,
    fivepaisa_user_id VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL,
    login_id VARCHAR(64) NOT NULL,
    client_code VARCHAR(64) NOT NULL,
    jwt_token VARCHAR(2048),
    jwt_expires_at TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    default_exchange VARCHAR(8) NOT NULL DEFAULT 'N',
    default_exchange_type VARCHAR(8) NOT NULL DEFAULT 'C',
    default_quantity INT NOT NULL DEFAULT 1,
    default_at_market BOOLEAN NOT NULL DEFAULT TRUE,
    default_is_intraday BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fivepaisa_users_active ON fivepaisa_users(active);

-- order_audit gets a broker column so 5paisa fan-out rows are distinguishable.
ALTER TABLE order_audit ADD COLUMN broker VARCHAR(16) NOT NULL DEFAULT 'zerodha';
