-- Application-level user accounts (distinct from broker credential rows).
--
-- Each row is a stocktrace login. Two roles: USER (default) and ADMIN.
-- New registrations start with active=false; an ADMIN must activate before
-- login succeeds.

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(128) NOT NULL UNIQUE,
    password_hash VARCHAR(128) NOT NULL,
    display_name VARCHAR(128),
    role VARCHAR(16) NOT NULL DEFAULT 'USER',
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_app_users_active ON app_users(active);
CREATE INDEX idx_app_users_role ON app_users(role);

-- Link the existing broker credential rows to their owning app_user so
-- self-trade / TradeOn flows can be scoped to the logged-in account only.
-- Existing rows (pre-migration) remain NULL and are treated as "legacy /
-- admin-managed" fan-out targets.
ALTER TABLE kite_users ADD COLUMN owner_app_user_id BIGINT;
ALTER TABLE kite_users
    ADD CONSTRAINT fk_kite_users_owner
    FOREIGN KEY (owner_app_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
CREATE INDEX idx_kite_users_owner ON kite_users(owner_app_user_id);

ALTER TABLE fivepaisa_users ADD COLUMN owner_app_user_id BIGINT;
ALTER TABLE fivepaisa_users
    ADD CONSTRAINT fk_fivepaisa_users_owner
    FOREIGN KEY (owner_app_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
CREATE INDEX idx_fivepaisa_users_owner ON fivepaisa_users(owner_app_user_id);
